version: '3'
services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: saklia
    volumes:
      - ./data/psql:/var/lib/postgresql/data
      - ./dev/docker_psql_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  mysql:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./dev/docker_mysql_init:/docker-entrypoint-initdb.d
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Example@1"
    ports:
      - 1433:1433


